# Use an official Nginx runtime as the base image
FROM nginx:alpine

# Copy HTML, CSS, and JS files to the Nginx server directory
COPY . /usr/share/nginx/html/

# Make port 80 available to the world outside this container
EXPOSE 80